# Generated by Django 3.0.8 on 2020-08-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200823_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mara_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sara_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
