# Generated by Django 3.0.8 on 2020-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200802_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pup_date',
            field=models.DateTimeField(default=None, verbose_name='date published'),
        ),
    ]
