# Generated by Django 3.0.8 on 2020-08-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200808_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('상의', '상의'), ('하의', '하의'), ('신발', '신발'), ('기타', '기타')], default=None, max_length=128, null=True),
        ),
    ]
