# Generated by Django 3.0.8 on 2020-10-07 11:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ckcontent',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
