# Generated by Django 3.0.8 on 2020-08-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('상의', '상의'), ('하의', '하의'), ('신발', '신발'), ('기타', '기타')], default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pup_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
