# Generated by Django 3.0.8 on 2020-08-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200808_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('상의', '상의'), ('하의', '하의'), ('신발', '신발'), ('기타', '기타')], default='상의', max_length=128),
        ),
    ]
