# Generated by Django 3.0.8 on 2020-08-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200808_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='link',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
