# Generated by Django 3.0.8 on 2020-08-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20200809_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(blank=True, default='NA', max_length=128, null=True),
        ),
    ]
