# Generated by Django 3.0.8 on 2020-08-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200809_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
