# Generated by Django 3.0.8 on 2020-08-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20200809_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='brand',
        ),
    ]
