# Generated by Django 3.0.8 on 2020-08-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_remove_post_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand',
            field=models.CharField(default='NA', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(default='NA', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.CharField(default='NA', max_length=128, null=True),
        ),
    ]
