# Generated by Django 3.0.8 on 2020-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200830_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mara',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sara',
            field=models.TextField(blank=True, null=True),
        ),
    ]
