# Generated by Django 3.0.8 on 2020-09-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200915_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mara_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sara_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
