# Generated by Django 3.0.8 on 2020-10-03 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20200926_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
