# Generated by Django 3.0.5 on 2020-11-08 10:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201108_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ckcontent',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
