# Generated by Django 3.0.5 on 2020-11-22 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_hitcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pup_date',
            new_name='pub_date',
        ),
        migrations.DeleteModel(
            name='HitCount',
        ),
    ]
