# Generated by Django 3.0.5 on 2020-11-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201122_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
