# Generated by Django 3.0.5 on 2020-11-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20201129_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_access_token',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
