# Generated by Django 3.0.5 on 2020-12-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20201129_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1900', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kakao_unique_id',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_nickname',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.CharField(blank=True, default='0101', max_length=128, null=True),
        ),
    ]
