# Generated by Django 3.0.5 on 2020-12-05 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewcount',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
