# Generated by Django 3.0.5 on 2020-12-18 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0032_auto_20201213_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 12, 18)),
        ),
    ]
