# Generated by Django 3.0.5 on 2020-12-18 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0033_auto_20201218_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1992', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 18, 13, 53, 24, 192998, tzinfo=utc)),
        ),
    ]
