# Generated by Django 3.0.5 on 2020-12-18 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0034_auto_20201218_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1999', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 12, 18)),
        ),
    ]
