# Generated by Django 3.0.5 on 2020-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0035_auto_20201218_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1958', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='view_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
