# Generated by Django 3.0.5 on 2020-12-18 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0036_auto_20201218_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1960', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
