# Generated by Django 3.0.5 on 2020-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0037_auto_20201218_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1953', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='viewcount',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
