# Generated by Django 3.0.5 on 2020-12-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0038_auto_20201218_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='author',
            new_name='loggedin_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1961', max_length=128, null=True),
        ),
    ]
