# Generated by Django 3.0.5 on 2020-12-26 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0041_auto_20201226_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mara_cnt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sara_cnt',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1970', max_length=128, null=True),
        ),
    ]
