# Generated by Django 3.0.5 on 2020-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0043_auto_20201226_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_cnt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mara',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sara',
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1976', max_length=128, null=True),
        ),
    ]
