# Generated by Django 3.0.5 on 2020-12-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0044_auto_20201226_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1964', max_length=128, null=True),
        ),
    ]
