# Generated by Django 3.0.5 on 2021-01-07 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0050_auto_20210101_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mara_users',
            field=models.ManyToManyField(related_name='mara_voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthyear',
            field=models.CharField(blank=True, default='1978', max_length=128, null=True),
        ),
    ]
